services:
  - type: web
    name: playwright-telegram-bot
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && playwright install --with-deps chromium"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
